CNN:
  name: ResNet # VanillaCNN or ResNet or DACNN or VGG16 or all. all will work only in train mode
  mode: test # train or test
  # multiple_plots: True
  model_configs:
    VanillaCNN:
      in_channels: 3
      out_channels: 32
      kernel: [3, 3]
      stride: 1
      padding: 'same'
      epochs: 10
      loss: 'ce'
    ResNet:
      num_classes: 10
      epochs: 12
      loss: 'ce'
    DACNN:
      num_classes: 10
      epochs: 12
      num_layers: 4
      loss: 'ce'
    VGG16:
      num_classes: 11
      epochs: 8
      num_layers: 4
      loss: 'ce'
  training_config:
    lr: 0.001
    batch_size: 64
    shuffle: True
  test_config:
    batch_size: 64
    shuffle: False   # Usually False for testing/evaluation
